### ISSUE TITLE
onconnect hook could not use agent

### ISSUE THREAD

**Issue by dawei101** [TooTallNate/proxy#10]
https://github.com/TooTallNate/proxy/blob/master/proxy.js#L411

net.connect  could not use server.agent  to finish the connect request

**Comment by TooTallNate** [comment]
I'm sorry, I don't get what you mean. Can you show me some example code of what you're trying to do?

**Comment by dawei101** [comment]
```
var server = setup(http.createServer(), {agent: SOME_SOCKS_PROXY});
```

When http proxy deal "CONNECT ***" request , it won't connect by "SOME_SOCKS_PROXY"

----------
I am in china, of course my computer can not open google.
I get an socks5 proxy that could open google
If I share with friends by http proxy by your repo, they still could not open google

Because below line does not connect through its parent proxy
https://github.com/TooTallNate/proxy/blob/master/proxy.js#L411

**Comment by andmeics** [comment]
Because the Great Firewall automatic deny the request,it isn't software problem
