### ISSUE TITLE
proxychains or upstream proxy

### ISSUE THREAD

**Issue by behrouz-s** [TooTallNate/proxy#12]
I have problem with making proxychain in nodejs.
I want to make proxy server that accept http and https requests and forward requests to another proxy that requires authentication.
for example:
client (https://www.yahoo.com) --> myproxy (nodejs proxy) --> my organization proxy (this proxy require username and password) --> Internet (https://www.yahoo.com).

Could you please help me with this issue?
Thanks in advace

**Comment by khang0001** [comment]
https://github.com/apifytech/proxy-chain
Try it?

**Comment by layerssss** [comment]
I've run into having to setup this as well. It turns out combining with this to setup a http agent could work. 

https://github.com/TooTallNate/node-proxy-agent

**Comment by TooTallNate** [comment]
This code in this repository has been moved to the [`proxy-agents` monorepo](https://github.com/TooTallNate/proxy-agents), so I am closing this pull request. If you feel that this issue still exists as of the latest release, feel free to open a new issue over there.
