### ISSUE TITLE
tunneling through external proxy

### ISSUE THREAD

**Issue by iatacodes** [TooTallNate/proxy#17]
Hi everyone,
I try to make a proxy server that will be proxify to another proxy...
If for the HTTP request I just add proxy agent 
[https://github.com/TooTallNate/proxy/blob/master/proxy.js#L197](https://github.com/TooTallNate/proxy/blob/master/proxy.js#L197)
like this:
`parsed.agent = new HttpProxyAgent("http://another_public_proxy:3128/");`

But it not works for HTTPS
[https://github.com/TooTallNate/proxy/blob/master/proxy.js#L428](https://github.com/TooTallNate/proxy/blob/master/proxy.js#L428)
when I try:
`opts.agent = new HttpsProxyAgent("http://another_public_proxy:3128/");`

I trying to do a proxy rotation between many external proxies...

**Comment by slowhog** [comment]
I have the same need so I put together a version to do this: https://github.com/slowhog/proxy, which should work with pac file or socks/http/https proxy.

Basically it use a Delegate interface to handle request and connect, and you can use delegateLookup to specify next chain. See the bin/proxyproxy.js for an example to use http proxy and bin/pacxy.js for change to use PAC file.

**Comment by TooTallNate** [comment]
This code in this repository has been moved to the [`proxy-agents` monorepo](https://github.com/TooTallNate/proxy-agents), so I am closing this pull request. If you feel that this issue still exists as of the latest release, feel free to open a new issue over there.
