### ISSUE TITLE
Add a throttle option

### ISSUE THREAD

**Issue by CashWilliams** [TooTallNate/proxy#8]
I'd like to use this proxy as a method to test site load times, but throttled both to represent realistic traffic and to limit the rate to a low enough rate to ensure tests are similar run to run (regardless of some network congestion).

My use case is starting the proxy and then having phantomjs run through it.

**Comment by TooTallNate** [comment]
This code in this repository has been moved to the [`proxy-agents` monorepo](https://github.com/TooTallNate/proxy-agents), so I am closing this pull request. If you feel that this issue still exists as of the latest release, feel free to open a new issue over there.
